config/routes.rb
Selectedrt::Application.routes.draw do
  resources :retweets

  get "twitter/show"

  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/retweet.rb
class Retweet < ActiveRecord::Base
  rescue Twitter::Error => e
  logger.error "#{e.message}."
  raise CouldNotRetweetError.new("Could not retweet")
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  # GET /retweets
  # GET /retweets.json
  def index
    @retweets = Retweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @retweets }
    end
  end

  # GET /retweets/1
  # GET /retweets/1.json
  def show
    @retweet = Retweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @retweet }
    end
  end

  # GET /retweets/new
  # GET /retweets/new.json
  def new
    @retweet = Retweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @retweet }
    end
  end

  # GET /retweets/1/edit
  def edit
    @retweet = Retweet.find(params[:id])
  end

  # POST /retweets
  # POST /retweets.json
  def create
    @retweet = Retweet.new(params[:retweet])

    respond_to do |format|
      if @retweet.save
        format.html { redirect_to @retweet, notice: 'Retweet was successfully created.' }
        format.json { render json: @retweet, status: :created, location: @retweet }
      else
        format.html { render action: "new" }
        format.json { render json: @retweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /retweets/1
  # PUT /retweets/1.json
  def update
    @retweet = Retweet.find(params[:id])

    respond_to do |format|
      if @retweet.update_attributes(params[:retweet])
        format.html { redirect_to @retweet, notice: 'Retweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @retweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retweets/1
  # DELETE /retweets/1.json
  def destroy
    @retweet = Retweet.find(params[:id])
    @retweet.destroy

    respond_to do |format|
      format.html { redirect_to retweets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController

  Twitter.configure do |config|
    config.consumer_key       = 'VBC8ZQVRtjRFgEjDOSfi8A'
    config.consumer_secret    = 'nHtXkVSJG6nh4SvJ5Y4g9FE0pOUhn52unvDsJ6eeqoU'
    config.oauth_token        = '439238568-NMlq1raEDjcgPUDGyN1lcXkQCaHSnZEMwzZk7oLU'
    config.oauth_token_secret = '47YOHfg6pr0Cgno4lf0H5Gj6x72FUNFn8fV8Pm4Y'
  end
  
  def show
    @accounts = Account.all
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
  
  ###
  # method that saves a retweet and returns if saved
  ###
  def save_distinct tweetid  
    exists = false
    retweets = Retweet.all
    
    # markup if retweet allready exists
    retweets.each do |retweet|
      if retweet.tweetid == tweetid
        exists = true
      end
    end
    
    # save retweet without markup
    if !exists
      retweet = Retweet.new(:tweetid => tweetid)
      retweet.save
      return true
    else
      return false
    end
  end
  
  
  ###
  # method that grabs all relevant tweets
  ###
  def get_tweetids
    d = Date.today.advance(:days => -1).strftime("%Y-%m-%d")
    tweetstatus = Array.new
    
    @accounts.each do |account|
      begin
        # get tweets of definded accounts of the last day
        result = Twitter.search("from:" + account.name + ", since:" + d, :result_type => "recent")
      rescue Twitter::Error::ClientError => e
        flash.now.alert = e.message
      end
      
      if result != nil
        result.results.map do |status|
          # tweet is no answer on anyone
          if status.in_reply_to_tweet_id == nil
            #tweet has correct url
            status.urls.each do |url|
              if url.expanded_url.include? account.url
                tweetstatus << status
              end
            end  
          end
        end
      end
    end

    return tweetstatus
  end
  
  
  def do_retweet
    get_tweetids.each do |status|
      saved = save_distinct(status.id.to_s)
      if saved
        begin
          Twitter.retweet(status.id)
        rescue CoundNotRetweetError => e
          flash.now.alert = e.message
        end
      end
    end
  end
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>
<h2>All existing accounts:</h2>

<table id="tablestyle">
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
<% accountCount = @accounts.count %>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= account.url %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %> |
<a href="/">Back to the Title</a>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @account.name %>
</p>

<p>
  <b>Url:</b>
  <%= @account.url %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>selectedRT - Retweet Officials only!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="page">
		<div id="sidebar">
			<ul id="sidebar-items">
			  <li>
				<h3>Links</h3>
				<ul class="links">
				  <li><a href="http://github.com/chrisnain/selectedrt">App on Github</a></li>
				  <li><a href="http://blog.cshelp.net">Developer Website</a></li>
				  <li><a href="http://twitter.com/Mitgezwitschert">Developer on Twitter</a></li>
				  <li><a href="http://flattr.com/profile/chrisnain">Developer on Flattr</a></li>
				</ul>
			  </li>
			</ul>
		</div>

		<div id="content">
			<div id="header">
			  <h1>selectedRT</h1>
			  <h2>Retweet Officials only!</h2>
			</div>
		
			<div id="getting-started">
			
				<%= yield %>
		
			</div>
		</div>

		<div id="footer">&nbsp;</div>
    </div>
</body>
</html>

app/views/retweets/_form.html.erb
<%= form_for(@retweet) do |f| %>
  <% if @retweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retweet.errors.count, "error") %> prohibited this retweet from being saved:</h2>

      <ul>
      <% @retweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweetid %><br />
    <%= f.number_field :tweetid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/retweets/edit.html.erb
<h1>Editing retweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @retweet %> |
<%= link_to 'Back', retweets_path %>

app/views/retweets/index.html.erb
<h1>Listing retweets</h1>
<h2>All previous retweets:</h2>

<table id="tablestyle">
  <tr>
    <th>Tweetid</th>
    <th></th>
  </tr>
  
<%#= accountCount = @retweets.count %>

<%# for i in 1 .. accountCount+1 %>
	<%#= Retweet.find(1).id %>
	<%#= @retweets.find(i) %>
<%# end %>

<% @retweets.each do |retweet| %>
  <tr>
    <td><%= retweet.tweetid %></td>
    <td><%= link_to 'Show', retweet %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Retweet', new_retweet_path %>
<a href="/">Back to the Title</a>

app/views/retweets/new.html.erb
<h1>New retweet</h1>

<%= render 'form' %>

<%= link_to 'Back', retweets_path %>

app/views/retweets/show.html.erb
<p id="notice"><%= notice %></p>

<% tweet = Twitter.status(@retweet.tweetid) %>

<p>
  <b>Tweetid:</b>
  <%= tweet.id %>
</p>
<p>
  <b><%= tweet.from_user %>:</b>
  <%= tweet.text %>
</p>

<%= link_to 'Back', retweets_path %>

app/views/twitter/show.html.erb
<h1>Twitter view</h1>
<h2>All tweets of the observed accounts:</h2>

<p>Shows the last tweets of the observed twitter accounts.</p><br />

<% get_tweetids.each do |status| %>
    <div id="tweet"><p><b>
	<%= "#{status.from_user}:" %></b>
	<%= "#{status.text} (#{status.id})" %>
	
    <% saved = save_distinct(status.id.to_s) %>
    <% if saved %>
    	<div id="tweetimage">
    		<img src=<%= asset_path "check.jpg" %> alt="retweeted">
		</div>
    	<% Twitter.retweet(status.id) %>
    <% else %>
    	<div id="tweetimage">
    		<img src=<%= asset_path "cross.jpg" %> alt="already retweeted" id="tweetimage">
		</div>
    <% end %>
    
    </p></div>
<% end %>

<br /><br />
<a href="/">Back to the Title</a>